# CPUs.
ifndef CPUS
  CPUS = 1
endif

BUILD_CPPFLAGS += -D K_CONFIG_CPUS=$(CPUS)

ifneq ($(CPUS),1)
  BUILD_CPPFLAGS += -D K_CONFIG_SMP
  export AP_BIN=ap.bin
endif

export CPUS

# Firmware - BIOS is default.
ifndef FIRMWARE
  FIRMWARE=BIOS
endif

ifeq ($(FIRMWARE),BIOS)
  BUILD_CPPFLAGS += -D K_CONFIG_BIOS
  FIRMWARE_TARGET := bios-grub-iso
else ifeq ($(FIRMWARE),UEFI)
  BUILD_CPPFLAGS += -D K_CONFIG_UEFI
  FIRMWARE_TARGET := uefi-grub
else
  $(error Unsupported firmware type (choose BIOS/UEFI))
endif

export FIRMWARE

# Architecture.
SYSTEM_ARCH = $(shell uname -p | sed -e s/i.86/x86/ -e s/x86_64/x86/)
ARCH ?= $(SYSTEM_ARCH)

ifeq ($(ARCH),x86)
  BUILD_CPPFLAGS += -D K_BITS_32
else
  $(error Unsupported architecture type)
endif

export ARCH

# Kernel stack size
BUILD_CPPFLAGS += -D K_CONFIG_STACK_SIZE=0x10000

