FINAL_CFLAGS := $(BUILD_CFLAGS) $(CFLAGS)

.PHONY: build
build: $(TARGETS)

%.o:%.S
	$(V)echo '  AS ' $(CURDIR)/$@
	$(V)$(CC) $(FINAL_CFLAGS) -c $^ -o $(BUILD_OBJDIR)/$(subst /,-,$(CURDIR))-$(notdir $@)

%.o:%.c
	$(V)echo '  CC ' $(CURDIR)/$@
	$(V)$(CC) $(FINAL_CFLAGS) -c $^ -o $(BUILD_OBJDIR)/$(subst /,-,$(CURDIR))-$(notdir $@)

