.PHONY := all
all:
	$(V)$(MAKE) -C utils/
	$(V)$(MAKE) -C pci/
	$(V)$(MAKE) -C irq/
	$(V)$(MAKE) -C acpi/
	$(V)$(MAKE) -C fb/
	$(V)$(MAKE) -C mm/
	$(V)$(MAKE) -C video/
	$(V)$(MAKE) -C modules/
	$(V)$(MAKE) -C initramfs/

