#ifndef MULTIBOOT2_H
#define MULTIBOOT2_H

#define MULTIBOOT2_HEADER_MAGIC	0xe85250d6

#define MULTIBOOT2_TAG_TYPE_END	0

#define MULTIBOOT2_ARCHITECTURE_I386	0
#define MULTIBOOT2_ARCHITECTURE_MIPS32	4

#endif

