#ifndef K_ERROR_H
#define K_ERROR_H

typedef enum {
	K_ERROR_NONE = 0,
	K_ERROR_FAILURE,
	K_ERROR_FATAL,
	K_ERROR_INVALID_PARAMETER,
	K_ERROR_ALREADY_INITIALIZED,
	K_ERROR_UNINITIALIZED,
	K_ERROR_UNSUPPORTED,
	K_ERROR_BAD_CHECKSUM,
	K_ERROR_INVALID_DEVICE,
	K_ERROR_NOT_FOUND,
	K_ERROR_MEMORY_ALLOCATION_FAILED,
	K_ERROR_INVALID_MODULE_HEADER,
	K_ERROR_INVALID_MODULE_SIZE,
	K_ERROR_INVALID_MODULE_INFO,
	K_ERROR_INVALID_MODULE_ELF,
	K_ERROR_MODULE_ALREADY_EXISTS,
	K_ERROR_UNEXPORTED_SYMBOL,
	K_ERROR_NONE_IRQ,
	K_ERROR_NETWORK_LINK_NOT_SET,
} k_error_t;

#endif

